// Generated by vscode
// Developer => Rafael Ferreira
// LinkedIn: linkedin.com/in/andersonrafaelferreira

/* 
{
  "name": "maps-selection",
  "version": "1.0.0",
  "description": "APi created to select city maps",
  "main": "maps.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/andersonrafaelferreira/map-selection.git"
  },
  "keywords": [
    "maps",
    "google",
    "selection",
    "stores",
    "api"
  ],
  "author": "Rafael Ferreira",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/andersonrafaelferreira/map-selection/issues"
  },
  "homepage": "https://github.com/andersonrafaelferreira/map-selection#readme"
}

*/
var _0x174c = [
  "createElement",
  "length",
  "createTextNode",
  "value",
  "maps",
  "mapa",
  "log",
  "appendChild",
  "cidade",
  "setAttribute",
  "filter",
  "then",
  "OPTION",
  "innerHTML",
  "disabled",
  "estado",
  "json",
  "https://api.sheety.co/13114ddb-a40c-46cc-89e6-dc3fc10eb989",
  "map",
  "getElementById"
];
(function(_0x3a85d1, _0x2f7ab7) {
  var _0x512a1e = function(_0x185f4c) {
    while (--_0x185f4c) {
      _0x3a85d1["push"](_0x3a85d1["shift"]());
    }
  };
  _0x512a1e(++_0x2f7ab7);
})(_0x174c, 0x8e);
var _0x1a7f = function(_0x3a85d1, _0x2f7ab7) {
  _0x3a85d1 = _0x3a85d1 - 0x0;
  var _0x512a1e = _0x174c[_0x3a85d1];
  return _0x512a1e;
};
list = "";
fetch(_0x1a7f("0xf"))
  ["then"](_0x39ed6c => _0x39ed6c[_0x1a7f("0xe")]())
  [_0x1a7f("0x9")](_0x1d75bc => {
    list = _0x1d75bc;
    solista();
    document[_0x1a7f("0x11")](_0x1a7f("0x3"))["innerHTML"] =
      _0x1d75bc[0x4][_0x1a7f("0x2")];
  });
unico = [];
function solista() {
  const _0x144707 = list[_0x1a7f("0x10")](
    _0x2d5c84 => _0x2d5c84[_0x1a7f("0xd")]
  );
  unico = new Set(_0x144707);
}
const estados = ["BA", "ES", "MG", "RJ", "SP", "GO"];
function carrega_estado() {
  document["getElementById"]("estado")[_0x1a7f("0xc")] = ![];
  for (i = 0x0; i < estados[_0x1a7f("0x13")]; i++) {
    var _0x4bcd43 = document[_0x1a7f("0x12")](_0x1a7f("0xa"));
    _0x4bcd43[_0x1a7f("0x7")](_0x1a7f("0x1"), estados[i]);
    var _0x374a13 = document[_0x1a7f("0x0")](estados[i]);
    _0x4bcd43[_0x1a7f("0x5")](_0x374a13);
    document[_0x1a7f("0x11")](_0x1a7f("0xd"))[_0x1a7f("0x5")](_0x4bcd43);
  }
}
function carrega_cidade(_0xc111e9) {
  document[_0x1a7f("0x11")]("cidade")[_0x1a7f("0xb")] = "";
  var _0x3a7197 = document[_0x1a7f("0x12")](_0x1a7f("0xa"));
  var _0x536f52 = document[_0x1a7f("0x0")]("Selecione\x20a\x20cidade");
  _0x3a7197["appendChild"](_0x536f52);
  document[_0x1a7f("0x11")]("cidade")[_0x1a7f("0x5")](_0x3a7197);
  document[_0x1a7f("0x11")]("cidade")[_0x1a7f("0xc")] = ![];
  for (i = 0x0; i < _0xc111e9[_0x1a7f("0x13")]; i++) {
    var _0x3a7197 = document[_0x1a7f("0x12")]("OPTION");
    _0x3a7197[_0x1a7f("0x7")](_0x1a7f("0x1"), _0xc111e9[i][_0x1a7f("0x2")]);
    var _0x536f52 = document[_0x1a7f("0x0")](_0xc111e9[i][_0x1a7f("0x6")]);
    _0x3a7197[_0x1a7f("0x5")](_0x536f52);
    document[_0x1a7f("0x11")](_0x1a7f("0x6"))[_0x1a7f("0x5")](_0x3a7197);
  }
}
function filtraCidade(_0x31eb51) {
  console[_0x1a7f("0x4")](list);
  const _0x476b17 = list[_0x1a7f("0x8")](
    _0x25f6cd => _0x25f6cd[_0x1a7f("0xd")] == _0x31eb51
  );
  console["log"](_0x476b17);
  carrega_cidade(_0x476b17);
}
function carregaMapa(_0x5bcc5f) {
  document[_0x1a7f("0x11")](_0x1a7f("0x3"))[_0x1a7f("0xb")] = _0x5bcc5f;
}
